# Generated by Django 5.2.7 on 2025-10-11 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(help_text='Token number (e.g. 163wwwww)', max_length=20)),
                ('title', models.CharField(help_text='Title (e.g. Nuisance)', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description (e.g. it was cool)')),
                ('date', models.DateField(help_text='Date (e.g. 12.12.2026)')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
