# Generated by Django 5.2.7 on 2025-10-11 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='token',
            options={'ordering': ['position'], 'verbose_name': 'Token', 'verbose_name_plural': 'Tokens'},
        ),
        migrations.AddField(
            model_name='token',
            name='position',
            field=models.IntegerField(db_index=True, default=0, unique=True, verbose_name='Position'),
        ),
        migrations.AddField(
            model_name='token',
            name='preview_image',
            field=models.ImageField(blank=True, null=True, upload_to='tokens/previews/', verbose_name='Preview image'),
        ),
        migrations.AddField(
            model_name='token',
            name='small_preview',
            field=models.BooleanField(default=False, verbose_name='Small preview'),
        ),
        migrations.AlterField(
            model_name='token',
            name='date',
            field=models.DateField(verbose_name='Token date'),
        ),
        migrations.AlterField(
            model_name='token',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='token',
            name='number',
            field=models.CharField(db_index=True, max_length=20, verbose_name='Token number'),
        ),
        migrations.AlterField(
            model_name='token',
            name='title',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Title'),
        ),
    ]
