# Generated by Django 5.2.7 on 2025-10-11 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_token_options_token_position_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='token',
            options={'verbose_name': 'Token', 'verbose_name_plural': 'Tokens'},
        ),
        migrations.RemoveField(
            model_name='token',
            name='position',
        ),
    ]
