# Generated by Django 5.2.7 on 2025-10-11 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_token_options_remove_token_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='header',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True, verbose_name='Header'),
        ),
    ]
