# Generated by Django 5.2.7 on 2025-10-11 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_token_header'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='description',
        ),
        migrations.RemoveField(
            model_name='token',
            name='title',
        ),
        migrations.AddField(
            model_name='token',
            name='title1',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Title1'),
        ),
        migrations.AddField(
            model_name='token',
            name='title2',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Title2'),
        ),
    ]
