# Generated by Django 5.2.7 on 2025-10-11 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_token_description_remove_token_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='title1',
        ),
        migrations.RemoveField(
            model_name='token',
            name='title2',
        ),
        migrations.AddField(
            model_name='token',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='token',
            name='title',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Title'),
        ),
    ]
